global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "devops_agent_api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["agent-api:8000"]

  - job_name: "docker_containers"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
